### ISSUE TITLE
Increase information to return errors messages via ZeroMQ

### ISSUE THREAD

**Issue by aleonlein** [AllenInstitute/ZeroMQ-XOP#18]
Error returns from MIES after executing a function call via the ZeroMQ proxy tend to look like this:

```json
{'errorCode': {'msg': 'CallFunction: The function was partially executed but '
                      'aborted at some point.',
               'value': 107},
 'messageID': 'Running in bath qc'}
```

without any useful information about why the error occurred. Can error messages be made more explicit when returned?

**Comment by t-b** [comment]
Note to self:
In general we don't know anything more than the fact that the function has aborted. But we can peek a the history and return what the function outputted.
